### ISSUE TITLE
playlists? 

### ISSUE THREAD

**Issue by osterland** [davidefavia/cordova-plugin-in-app-youtube#3]
Hey, 

is it possible to open a playlist instead of a single video? 

regards, 

Kevin

**Comment by osterland** [comment]
yes it is ;) 

InAppYouTube.openVideo('watch?v=e_D5rlZ4vhA&index=1&list=PL034gi3Deg-SaUUB5xoHc6hpQNDU-JXWf');

**Comment by davidefavia** [comment]
Thanks, never tried before. Will check pros and cons on different platforms and I eventually add more explicit docs, it could be useful.
