### ISSUE TITLE
Implement this in Ionic 2+???

### ISSUE THREAD

**Issue by damonsomu** [davidefavia/cordova-plugin-in-app-youtube#4]
Is there any way to implement this in Ionic 2+?? if yes, how??

**Comment by davidefavia** [comment]
Hi @damonsomu,
you can of course use it with Ionic 2+ (I'm using it with version 3.9.2):

1. install plugin via `cordova` or `ionic cordova`,
2. use it accessing method via `window.InAppYouTube` or create an Angular service as a wrapper.

**Comment by damonsomu** [comment]
Any example??
